67. update the node runners private node creation page colours and skin tones
cartesi/explorer pull request #114
Opened 2023-08-22 04:29 UTC by dandheedge

Fixes #67 #69

2023-08-28 03:09 UTC, brunomenezes requested changes
Hi @dandheedge, 
As you are solving two issues in one PR, here is what I caught on both pages. 

## Private node creation

The first is that links are not using the `dark secondary` colour (teal) you can see the definition on Figma [here](https://www.figma.com/file/WuitYyfH2w4a5tnhXK6aRC/Explorer-design-system?type=design&node-id=2028-6389&mode=design&t=nAfv9Buf5u31BrHX-0) also, by the case stated on Figma the link text should be teal and not cyan (I saw a few). An example on that page is the top link for the tutorial and inside the `Set up Node` box (Reference below).

The second is that the steps counter on the **small devices version** still displays the old colours and tones (reference below)

#### Links
![links-not-using-secondary-dark(teal)](https://github.com/cartesi/explorer/assets/1239768/a005e009-3493-4386-a2a4-67a48fa8a997)

#### Step status on small devices
![private-node-creation](https://github.com/cartesi/explorer/assets/1239768/eccc0066-4e25-4857-85ef-1f3ed472b29c)

## Private node management
Things look good. One thing I caught here is that the **allowance** notification/alert is not displaying anymore when the confirmation is sent to the wallet [Reference below]. 

![no-allowance-alert](https://github.com/cartesi/explorer/assets/1239768/37328a1c-c8c7-4335-91fb-05946ac499ae)

2023-09-04 05:04 UTC, nevendyulgerov commented on apps/staking/src/components/node/NodeHireNodeSection.tsx
> +    const bg = useColorModeValue('white', 'rgba(255, 255, 255, 0.06)');
If possible, please add a color var for `rgba(255, 255, 255, 0.06)` and reference it from the colors config instead.

2023-09-04 05:05 UTC, nevendyulgerov commented on apps/staking/src/components/node/NodeHireNodeSection.tsx
> +            border="1px solid rgba(255, 255, 255, 0.10)"
I think we have a color var for `rgba(255, 255, 255, 0.10)`. Please check the colors config.

2023-09-04 05:05 UTC, nevendyulgerov commented on apps/staking/src/components/node/NodeInfoSection.tsx
> +    const bgBox = useColorModeValue('white', 'rgba(255, 255, 255, 0.06)');
Please use a color var instead.

2023-09-04 05:06 UTC, nevendyulgerov commented on apps/staking/src/components/node/NodeInfoSection.tsx
> +                        border={'1px solid rgba(255, 255, 255, 0.10)'}
Same here.

2023-09-04 05:07 UTC, nevendyulgerov commented on apps/staking/src/components/node/NodeMaturingSection.tsx
> +    const bg = useColorModeValue('white', 'rgba(255, 255, 255, 0.06)');
Here as well for using a color var.

2023-09-04 05:08 UTC, nevendyulgerov commented on apps/staking/src/components/node/NodeMaturingSection.tsx
> +            border="1px solid rgba(255, 255, 255, 0.10)"
And here.

2023-09-04 05:08 UTC, nevendyulgerov commented on apps/staking/src/components/node/NodeReleasingSection.tsx
> +    const bg = useColorModeValue('white', 'rgba(255, 255, 255, 0.06)');
And here.

2023-09-04 05:08 UTC, nevendyulgerov commented on apps/staking/src/components/node/NodeReleasingSection.tsx
> +            border="1px solid rgba(255, 255, 255, 0.10)"
Here as well.

2023-09-04 05:09 UTC, nevendyulgerov commented on apps/staking/src/components/node/NodeStakedBalanceSection.tsx
> +    const bg = useColorModeValue('white', 'rgba(255, 255, 255, 0.06)');
And here.

2023-09-04 05:09 UTC, nevendyulgerov commented on apps/staking/src/components/node/NodeStakedBalanceSection.tsx
> +            border="1px solid rgba(255, 255, 255, 0.10)"
Here as well for color var.

2023-09-04 05:09 UTC, nevendyulgerov commented on apps/staking/src/components/node/modals/NodeAllowanceModal.tsx
> +                    border={'1px solid rgba(255, 255, 255, 0.20)'}
Here as well for a color var.

2023-09-04 05:10 UTC, nevendyulgerov commented on apps/staking/src/components/node/modals/NodeBalanceModal.tsx
> +                    border={'1px solid rgba(255, 255, 255, 0.20)'}
Here as well for a color var.

2023-09-04 05:10 UTC, nevendyulgerov commented on apps/staking/src/components/node/modals/NodeRetireModal.tsx
> +                border={'1px solid rgba(255, 255, 255, 0.20)'}
Here as well for a color var.

2023-09-04 05:10 UTC, nevendyulgerov commented on apps/staking/src/components/node/modals/NodeStakeModal.tsx
> +                    border={'1px solid rgba(255, 255, 255, 0.20)'}
Here as well.

2023-09-04 05:10 UTC, nevendyulgerov commented on apps/staking/src/components/node/modals/NodeUnstakeModal.tsx
> +                    border={'1px solid rgba(255, 255, 255, 0.20)'}
Here as well for a color var.

2023-09-04 05:11 UTC, nevendyulgerov commented on apps/staking/src/components/node/steps/CustomizeEthereumNode.tsx
> +    const bg = useColorModeValue('teal.light', 'rgba(255, 255, 255, 0.06)');
Here and below, please use a color var instead.

2023-09-04 05:11 UTC, nevendyulgerov commented on apps/staking/src/components/node/steps/CustomizeEthereumNode.tsx
> +                        colorScheme={colorMode === 'dark' ? 'cyan' : 'teal'}
You can use `useColorModeValue` for the color scheme as well.

2023-09-04 05:12 UTC, nevendyulgerov commented on apps/staking/src/components/node/steps/HireNode.tsx
> +    const tipsBgColor = useColorModeValue('white', 'rgba(255, 255, 255, 0.20)');
Same here for a color var.

2023-09-04 05:12 UTC, nevendyulgerov commented on apps/staking/src/components/node/steps/HireNode.tsx
> +        'rgba(255, 255, 255, 0.10)'
And here.

2023-09-04 05:12 UTC, nevendyulgerov commented on apps/staking/src/components/node/steps/HireNode.tsx
> +                        colorScheme={colorMode === 'dark' ? 'cyan' : 'teal'}
Please use `useColorModeValue` for the color scheme.

2023-09-04 05:12 UTC, nevendyulgerov commented on apps/staking/src/components/node/steps/SetAllowance.tsx
> +    const bg = useColorModeValue('teal.light', 'rgba(255, 255, 255, 0.06)');
Here and below, please use a color var instead.

2023-09-04 05:13 UTC, nevendyulgerov commented on apps/staking/src/components/node/steps/SetAllowance.tsx
> +                        colorScheme={colorMode === 'dark' ? 'cyan' : 'teal'}
Same as above, please use `useColorModeValue` instead.

2023-09-04 05:13 UTC, nevendyulgerov commented on apps/staking/src/components/node/steps/SetUpNode.tsx
> +    const bgColor = useColorModeValue('white', 'rgba(255, 255, 255, 0.20)');
Here as well for a color var.

2023-09-04 05:13 UTC, nevendyulgerov commented on apps/staking/src/components/node/steps/SetUpNode.tsx
> +    const bg = useColorModeValue('teal.light', 'rgba(255, 255, 255, 0.06)');
And here, as well as below. Please use a color var.

2023-09-04 05:13 UTC, nevendyulgerov commented on apps/staking/src/components/node/steps/SetUpNode.tsx
> +                        colorScheme={colorMode === 'dark' ? 'cyan' : 'teal'}
Please use `useColorModeValue` here.

2023-09-04 05:14 UTC, nevendyulgerov commented on apps/staking/src/components/stake/components/StakedBalanceSection.tsx
> +            border="1px solid rgba(255, 255, 255, 0.10)"
Here as well for a color var.

2023-09-04 05:14 UTC, nevendyulgerov commented on apps/staking/src/pages/node/[node]/manage.tsx
> +    const bgBox = useColorModeValue('white', 'rgba(255, 255, 255, 0.06)');
Here as well.

2023-09-05 15:53 UTC, nevendyulgerov approved these changes

2023-09-06 07:30 UTC, merged